export default[
{id:1,image:'https://images.unsplash.com/photo-1578763872782-8d429b47532f?ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDM2fHRvd0paRnNrcEdnfHxlbnwwfHx8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',name:'Jason Roy',age:24,occupation:"IT",bio:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo magna mi, quis elementum quam hendrerit sed. Donec et ultrices lacus, non rutrum felis. Aliquam aliquet eros enim, porttitor venenatis nisi elementum vitae. In non varius erat. Integer faucibus ante quis suscipit sodales. Nulla quis dolor vitae tellus accumsan condimentum ut faucibus arcu. Cras mattis lacus eu ex fermentum fringilla. Pellentesque et tortor nisi.'},
{id:2,image:'https://images.unsplash.com/photo-1544159729-c9380464148c?ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDM4fHRvd0paRnNrcEdnfHxlbnwwfHx8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',name:'Jason Roy',age:24,occupation:"CS",bio:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo magna mi, quis elementum quam hendrerit sed. Donec et ultrices lacus, non rutrum felis. Aliquam aliquet eros enim, porttitor venenatis nisi elementum vitae. In non varius erat. Integer faucibus ante quis suscipit sodales. Nulla quis dolor vitae tellus accumsan condimentum ut faucibus arcu. Cras mattis lacus eu ex fermentum fringilla. Pellentesque et tortor nisi.'},
{id:3,image:'https://images.unsplash.com/photo-1512850692650-c382e34f7fb2?ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDM3fHRvd0paRnNrcEdnfHxlbnwwfHx8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',name:'Jason Roy',age:24,occupation:"ME",bio:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo magna mi, quis elementum quam hendrerit sed. Donec et ultrices lacus, non rutrum felis. Aliquam aliquet eros enim, porttitor venenatis nisi elementum vitae. In non varius erat. Integer faucibus ante quis suscipit sodales. Nulla quis dolor vitae tellus accumsan condimentum ut faucibus arcu. Cras mattis lacus eu ex fermentum fringilla. Pellentesque et tortor nisi.'},
{id:4,image:'https://images.unsplash.com/photo-1618842269111-508e4e1b6691?ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDQ2fHRvd0paRnNrcEdnfHxlbnwwfHx8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',name:'Jason Roy',age:24,occupation:"CSE",bio:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo magna mi, quis elementum quam hendrerit sed. Donec et ultrices lacus, non rutrum felis. Aliquam aliquet eros enim, porttitor venenatis nisi elementum vitae. In non varius erat. Integer faucibus ante quis suscipit sodales. Nulla quis dolor vitae tellus accumsan condimentum ut faucibus arcu. Cras mattis lacus eu ex fermentum fringilla. Pellentesque et tortor nisi.'},
{id:5,image:'https://images.unsplash.com/photo-1588946653163-7c781a0f6702?ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDU3fHRvd0paRnNrcEdnfHxlbnwwfHx8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',name:'Jason Roy',age:24,occupation:"Material",bio:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo magna mi, quis elementum quam hendrerit sed. Donec et ultrices lacus, non rutrum felis. Aliquam aliquet eros enim, porttitor venenatis nisi elementum vitae. In non varius erat. Integer faucibus ante quis suscipit sodales. Nulla quis dolor vitae tellus accumsan condimentum ut faucibus arcu. Cras mattis lacus eu ex fermentum fringilla. Pellentesque et tortor nisi.'},
{id:6,image:'https://images.unsplash.com/photo-1599139497043-042b5c90db45?ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE2fHRvd0paRnNrcEdnfHxlbnwwfHx8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',name:'Jason Roy',age:24,occupation:"Material",bio:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo magna mi, quis elementum quam hendrerit sed. Donec et ultrices lacus, non rutrum felis. Aliquam aliquet eros enim, porttitor venenatis nisi elementum vitae. In non varius erat. Integer faucibus ante quis suscipit sodales. Nulla quis dolor vitae tellus accumsan condimentum ut faucibus arcu. Cras mattis lacus eu ex fermentum fringilla. Pellentesque et tortor nisi.'},

];
